### ISSUE TITLE
MapsPrinter - Can't export to PDF

### ISSUE THREAD

**Issue by nwdejong** [DelazJ/MapsPrinter#13]
Hello MapsPrinter,

I have a problem with the plugin on QGIS 3.4. Have used it before on QGIS 2.18. Really need it for a batchplot for my project. I hope you can fix it or help me out in one way. It's eather a bug or I cam doing something wrong :) Thanks for the awesome plugin, great job!

![2019-03-19_17h57_46](https://user-images.githubusercontent.com/48735650/54641548-373cc480-4a71-11e9-9a46-44c685b57d48.png)

**Comment by DelazJ** [comment]
@nwdejong i'm afraid i don't understand the report. The message on top of the canvas should appear only when you hit "Cancel" while exporting. Without information on when it appears, what you do before it shows nor how it affects the export (if that's your actual issue), i don't know what to do. 
Thanks for using the plugin.

**Comment by nwdejong** [comment]
@DelazJ I have downloaded from another page a zipped plugin that did work. Mapsprinter is now 2 times installed on my QGIS 3.4 but it works. I am very happy with it, saves me a lot of time. You want me to sent you the .zip file? Thanks for your quick response!

**Comment by DelazJ** [comment]
Glad that works and saves you time.  Yes, could you send me the link you downloaded it from, please? And also how did you install it the first time?

**Comment by nwdejong** [comment]
[MapsPrinter-master.zip](https://github.com/DelazJ/MapsPrinter/files/3004979/MapsPrinter-master.zip)

This is the zipfile that i used, forgot the page where i downloaded it from.
