### ISSUE TITLE
Fix for world file not being generated

### ISSUE THREAD

**Issue by mpergler** [DelazJ/MapsPrinter#14]
Hi there. Downloaded yesterday for QGIS 3.6.2 (Windows). Super plugin!

I have found and solved one issue - when exporting to png, a layout's setting to generate a world file was not being respected. 

The problem was in `maps_printer.py`, `overrideExportSetings()`. The current code
`if layout.customProperty('exportWorldFile') == True : exportSettings.generateWorldFile = True`
need to be changed to
`if layout.customProperty('exportWorldFile') == 'true' : exportSettings.generateWorldFile = True`
since the output of customProperty is a string not a boolean.

Not sure if this was a typo, or if these undocumented custom properties have changed since when you programmed it. In any case, for me with the above change it is fixed.

**Comment by DelazJ** [comment]
Hummm, Looking for the occurrences of `exportworldfile` in the code, I found https://github.com/qgis/QGIS/blob/release-3_6/src/app/layout/qgslayoutpropertieswidget.cpp#L60 and it sounds like a boolean.
Anyway, will give it a look later. Thanks for providing a fix.

**Comment by mpergler** [comment]
Hmm. Am just looking briefly in transit on my phone, but that 3.6 src line has .toBool at the end which may be forcing the translation - maybe that’s the solution. In any case I’ve added the string test and kept the bool test too and it’s working for me.
