### ISSUE TITLE
Maps Printer does not respect the resolution set in the Print Layout

### ISSUE THREAD

**Issue by peterbishop88** [DelazJ/MapsPrinter#15]
It looks like if I set a lower Export Resolution (250DPI under Export Settings > Export Resolution) for the PDF in the Print Layout (to reduce file size), it still exporting a higher res version (Print as Raster = TRUE). 

For example, when I use Maps Printer, the file generated is 241MB. When I export manually from the Print Composer (Layout > Export PDF), the resulting file is 14MB.

**Comment by peterbishop88** [comment]
Does anyone have any advice on this? Or does anybody have a workaround? Thanks!

**Comment by DelazJ** [comment]
Hi @peterbishop88 
Sorry for the late reply. I just made a quick try on a print layout and I can not reproduce the issue; I get the same size as if exported from print layout dialogs (tested with 300, 250 and 150 dpi). The size changed in the three cases and coherent with direct output.
Also tried with unchecking the "print as raster" and got same size.
I'd need more input. Any project file you can share with me at delazj at gmail dot com?

**Comment by DelazJ** [comment]
Ah... Are you using some effects on your composition or data?

**Comment by peterbishop88** [comment]
Hello! No, I'm not using any effects. I've attached a step-by-step to reproduce, as well as some example files. Let me know if you have any questions! Thanks so much for looking into this. 

To summarize my issue - I expect the file size from the Maps Printer plugin to match the file size when I do Export to PDF in the Layout Manager. Is this the intended behavior? 


[QGIS Bug Report.zip](https://github.com/DelazJ/MapsPrinter/files/3349986/QGIS.Bug.Report.zip)
[Map Printer step by step file size.docx](https://github.com/DelazJ/MapsPrinter/files/3349987/Map.Printer.step.by.step.file.size.docx)

**Comment by peterbishop88** [comment]
Hi @DelazJ , I was wondering if you had any luck at reproducing my issue (or the time to do it!) with the steps in the Word Doc above? Let me know if you need any additional information on my end. Thanks! 
PS I love this plugin and I use it every day at work.

**Comment by DelazJ** [comment]
Hi @peterbishop88
Yes I did test and reproduced your issue. Happened that I did not properly get the GUI settings such as the raster tick box. Would you mind giving a shot to https://github.com/DelazJ/MapsPrinter/blob/fixrasterizeexport/maps_printer.py (replace the file in your plugin folder with that one)? The file should be accessible through QGIS `Settings -> User Profiles -> Open Active Profile Folder` then `python/plugins/MapsPrinter` folder.
You'd "need" to reload QGIS

**Comment by peterbishop88** [comment]
Hi @DelazJ ! 

Amazing!! Thank you SO much. I really appreciate it. Your update works great. 

 I love this plugin. My composers take a long time to load, so your plugin lets me export them without having to wait for them to load. 

Peter

**Comment by DelazJ** [comment]
> Amazing!! Thank you SO much. I really appreciate it. Your update works great.

Glad it did it. I will need to check other formats behavior and will release a new version.
> I love this plugin. My composers take a long time to load, so your plugin lets me export them without having to wait for them to load.

Thanks. This originally is the reason why I wrote this plugin. And happy that's still useful.
