### ISSUE TITLE
Export at different DPI settings

### ISSUE THREAD

**Issue by joshpk** [DelazJ/MapsPrinter#17]
Hi. First, thank you for the great plug-in, I find it to be a big time saver for me. My issue is that I have a setup with many different print layouts and I would like to be able to export all of them at varying DPI. By default, each layout is set to 300 DPI, but to change it involves opening every layout and adjusting the DPI setting (and then reverting that if there is a need to re-export at the old DPI). Is there any way of adding a DPI setting to the Maps Printer to allow for a global change of DPI on export?
Thanks.

**Comment by DelazJ** [comment]
Sounds like an interesting feature request. I'll try but i can guarantee you a quick implementation.

**Comment by joshpk** [comment]
Thanks so much for this! Very helpful.

**Comment by DelazJ** [comment]
@joshpk did you test it?

**Comment by joshpk** [comment]
I was just exploring the latest updates and realized I never replied here, sorry. I did test it, and have been using it for some time. Its a great help and I really appreciate the plugin!
