### ISSUE TITLE
XMDF vector arrow handling in PDF 3.12+

### ISSUE THREAD

**Issue by nigelwest** [DelazJ/MapsPrinter#36]
The 'display vector on user grid' is ignored when batch printing to PDF where the layout map windows include TUFLOW generated XMDF layers. This occurs in versions 3.12 and 3.14. While version 3.10 appears to function correctly the density of vector arrows in the map window do not match the vector density of the printed PDF layout (WYSIWYG mismatch).
Incorporation of a batch-print function in QGIS core would be very welcome!

**Comment by DelazJ** [comment]
@nigelwest Sorry but I do not understand what the report is about, and how/whether it relates to Maps Printer plugin. Any clarification and details with steps to reproduce your issue would be welcome. Thanks.
