### ISSUE TITLE
Field with formula in layout does not update

### ISSUE THREAD

**Issue by mickmm** [DelazJ/MapsPrinter#37]
I have layouts containing HTML elements with formula like this: [%@layout_name%]

The formulas does not update/show on the exported pdf .

I solved the problem adding a line to refresh the layout before printing: **exporter.layout().refresh()** 
…..

        # Do the export process
        exporter = QgsLayoutExporter(cView)
        
        #refresh the layout before printing
        exporter.layout().refresh()

        # Allow export cancelation
        QCoreApplication.processEvents()
        self.dlg.buttonBox.rejected.connect(self.stopProcessing)
….

I tested a normal layout and it worked. I did not test it with atlas. 

Could you update update the code?

I would appreciate if you mention my name with this small (but important) contribution.

Regards

**Comment by DelazJ** [comment]
Thanks. Fixed in 2fdeccf
