### ISSUE TITLE
Naming conflict when exporting to png. 

### ISSUE THREAD

**Issue by HughKelley** [DelazJ/MapsPrinter#38]
Just want to log this as an issue since I figured out a solution that may be useful to others. 

Feel free to close. 

If I export multiple atlas layouts to pdf, the pdf is given the layout name, with a page for each atlas view. If I export the atlases to PNG, the images are named after each of the atlas page names. 

I'm using the same geometry layer to define the pages of the two atlases. This means image exports saved over each other since they have the same name across different layouts. 

To dynamically name the pages of the atlas after the layout name plus the page name:

1. In the Atlas Settings tab in the layout window, change "Output filename expression" to:
 ` to_string(@layout_name) + '_' + to_string("Name")`

**Comment by DelazJ** [comment]
@hughKelley This is not a MapsPrinter issue, is it? If you were exporting directly from print layout dialog, different atlases to the same folder, you would hit the same issue, right? In which case, I'm not sure that keeping it as a MapsPrinter issue is worth it.

**Comment by HughKelley** [comment]
> @HughKelley This is not a MapsPrinter issue, is it? 

No, just wanted to add it here as other MapsPrinter users might run into it as I did. 

As i said, feel free to just close it.
