### ISSUE TITLE
Algorithm from a folder is not available

### ISSUE THREAD

**Issue by gregbodet** [DelazJ/MapsPrinter#41]
**Describe the bug**

After installing the MapsPrinters Master Plugin from the ZIP in QGIS 3.16, the export algorithm from a folder is not available in the plugin options. Only the grouped layout export is available.

**Comment by DelazJ** [comment]
Hello,
Comme indiqué dans le fil georezo, j'ai fait le test: l'installation se fait bien avec les deux algos. Comment avez-vous installé?
![Capture d’écran 2021-07-02 à 09 49 24](https://user-images.githubusercontent.com/7983394/124244820-a2feaa80-db1f-11eb-950d-e2ad642d069f.png)

**Comment by gregbodet** [comment]
Bonjour,
Dans QGIS 3.16, je suis passé par le Menu Extension => Installer/Gérer les extensions => Installer depuis un ZIP (indication du ZIP télécharger sur le Git). Pas de messages à l'installation, 

Puis dans Extension, je n'ai qu'un algorithme. 
![image](https://user-images.githubusercontent.com/37414914/124248049-c1b27080-db22-11eb-8f5d-23b028ba057c.png)

Cordialement

**Comment by DelazJ** [comment]
Ce n'est pas la dernière version que vous avez téléchargée, là! Ca, c'est la vieille version officielle (=<0.5)

Pour télécharger la bonne version master, 
1. vous allez sur la page d'accueil (https://github.com/DelazJ/MapsPrinter)
2. Vous cliquez sur le bouton vert "Code" et dans la liste déroulante, vous choisissez "Download zip" (vous devez obtenir un fichier MapsPrinter-master.zip)
3. Et réessayez votre procédure avec ce fichier, pour voir.

**Comment by gregbodet** [comment]
Bonjour,

Je viens de faire la procédure, et j’ai un message d’erreur

Impossible de charger l'extension 'MapsPrinter-master' provoque une erreur lors de l'appel à sa méthode classFactory()
ModuleNotFoundError: No module named 'MapsPrinter'
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter-master\__init__.py", line 34, in classFactory
    from .maps_printer import MapsPrinter
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter-master\maps_printer.py", line 32, in
    from .processing_provider.maps_printer_provider import MapsPrinterProvider
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter-master\processing_provider\maps_printer_provider.py", line 31, in
    from .export_layouts_from_project import ExportLayoutsFromProject
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter-master\processing_provider\export_layouts_from_project.py", line 40, in
    from MapsPrinter.gui_utils import GuiUtils
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'MapsPrinter'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Version de QGIS : 3.16.8-Hannover Hannover, 8c50902ea4
Chemin Python :
·                     C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
·                     C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python
·                     C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
·                     C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
·                     C:\Program Files\QGIS 3.16\bin\python37.zip
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
·                     C:\Program Files\QGIS 3.16\bin
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
·                     C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python
·                     C:\Users\gbodet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\forms
·                     C:\Users\gbodet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
·                     C:\Users\gbodet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
·                     C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\gbodet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res

Cordialement

[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.***
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 10:55
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Ce n'est pas la dernière version que vous avez téléchargé, là! Ca, c'est la vieille version officielle (=<0.5)

Pour télécharger la bonne version master,

  1.  vous allez sur la page d'accueil (https://github.com/DelazJ/MapsPrinter)
  2.  Vous cliquez sur le bouton vert "Code" et dans la liste déroulante, vous choisissez "Download zip" (vous devez obtenir un fichier MapsPrinter-master.zip)
  3.  Et réessayez votre procédure avec ce fichier, pour voir.

**Comment by gregbodet** [comment]
Re-Bonjour,

Quand je recharge QGIS 3.16, voici le message indiqué :

2021-07-02T10:58:33     WARNING    dir = C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
2021-07-02T10:58:34     INFO    État de l'application
             variable d'environnement QGIS_PREFIX_PATH : C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr
             Préfixe: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr
             Chemin des extensions: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/plugins
             Chemin des paquets de données: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/.
             Nom du thème actif: default
             Chemin du thème actif: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./resources/themes\default\icons/
             Chemin du thème par défaut: :/images/themes/default/
             Chemins de recherche SVG: C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./svg/
              C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
              C:\Users\gbodet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\styles/classique/svg
              C:/PROGRA~1/QGIS3.10/apps/qgis-ltr/./svg/
              C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./svg/
             Chemin de la BD utilisateur: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./resources/qgis.db
             Chemin de la BD d'authentification: C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db

Cordialement

[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.***
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 10:55
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Ce n'est pas la dernière version que vous avez téléchargé, là! Ca, c'est la vieille version officielle (=<0.5)

Pour télécharger la bonne version master,

  1.  vous allez sur la page d'accueil (https://github.com/DelazJ/MapsPrinter)
  2.  Vous cliquez sur le bouton vert "Code" et dans la liste déroulante, vous choisissez "Download zip" (vous devez obtenir un fichier MapsPrinter-master.zip)
  3.  Et réessayez votre procédure avec ce fichier, pour voir.

**Comment by DelazJ** [comment]
OK, J'ai jamais réussi avec cet outil d'installation zip, mais désinstallez le plugin et réessayez après avoir renommé le zip en MapsPrinter.zip tout court

**Comment by DelazJ** [comment]
Une autre option d'installation (celle que j'utilise) est de:
1. Dézipper le fichier téléchargé et renommer le nouveau dossier en `MapsPrinter`
1. Aller dans menu Préférences --> Profis Utilisateurs --> Ouvrir le dossier du profil actif
1. Dans ce dossier, naviguer vers `python/plugins` et y coller le dossier `MapsPrinter`
1. Relancer QGIS

**Comment by gregbodet** [comment]
J’ai bien les 2 algorithmes de disponible maintenant mais aucun ne fonctionne même en chargeant un projet avec un atlas, et je n’ai aucun message d’erreur.
Après avoir cliqué sur Exécuter la fenêtre se ferme.

La version antérieure fonctionnait très bien pour exporter les atlas du projet sélectionné.

Cordialement

[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.***
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 11:09
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Une autre option d'installation (celle que j'utilise) est de:

  1.  Dézipper le fichier téléchargé et renommer le nouveau dossier en MapsPrinter
  2.  Aller dans menu Préférences --> Profis Utilisateurs --> Ouvrir le dossier du profil actif
  3.  Dans ce dossier, naviguer vers python/plugins et y coller le dossier MapsPrinter
  4.  Relancer QGIS

**Comment by gregbodet** [comment]
Bonjour,

Après de nouveaux essais, j’ai réussi à faire fonctionner l’algorithme pour exporter les atlas contenus dans un projet, mais c’est format PDF quui fait planté. Si je mets PNG cela fonctionne.

L’algorithme pour exporter les atlas contenus dans des dossiers fonctionne également mais le même problème de format, le PDF plante et le PNG passe.

Voici le message renvoyé dans le journal :

Traceback (most recent call last):
File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter\processing_provider\export_layouts_from_folder.py", line 139, in processAlgorithm
'\nERROR: No valid extension selected for output. We cannot continue...\n'
TypeError: reportError() missing 1 required positional argument: 'fatalError'

Cordialement


[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.***
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 11:09
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Une autre option d'installation (celle que j'utilise) est de:

  1.  Dézipper le fichier téléchargé et renommer le nouveau dossier en MapsPrinter
  2.  Aller dans menu Préférences --> Profis Utilisateurs --> Ouvrir le dossier du profil actif
  3.  Dans ce dossier, naviguer vers python/plugins et y coller le dossier MapsPrinter
  4.  Relancer QGIS

**Comment by gregbodet** [comment]
Après de nouveaux essais, j’ai réussi à faire fonctionner l’algorithme pour exporter les atlas contenus dans un projet, mais c’est le format PDF qui fait planté. Si je mets PNG cela fonctionne. 

L’algorithme pour exporter les atlas contenus dans des dossiers fonctionne également mais le même problème de format, le PDF plante et le PNG passe.

Voici le message renvoyé dans le journal :

Traceback (most recent call last):
File "C:/Users/gbodet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MapsPrinter\processing_provider\export_layouts_from_folder.py", line 139, in processAlgorithm
'\nERROR: No valid extension selected for output. We cannot continue...\n'
TypeError: reportError() missing 1 required positional argument: 'fatalError'

**Comment by DelazJ** [comment]
Je pense avoir corrigé le bug. Réessayez avec la nouvelle version.

**Comment by gregbodet** [comment]
Bonjour,

Je viens de réessayer, cela fonctionne. En revanche, on ne peut pas personnaliser le nom de sortie du fichier. Par défaut il concatène le nom du projet et le nom de la mise en page. Pour des améliorations futures, il serait intéressant de pouvoir exporter que le nom paramétré dans l’atlas.

Cordialement

[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.***
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 12:24
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Je pense avoir corrigé le bug. Réessayez avec la nouvelle version.

**Comment by DelazJ** [comment]
> Pour des améliorations futures, il serait intéressant de pouvoir exporter que le nom paramétré dans l’atlas.

Ce devrait être bon, avec les nouveaux changements.

**Comment by gregbodet** [comment]
Bonjour,

En voulant me servir de nouveau du Plugin MapsPrinter sur la dernière version LTR de QGIS, je n’arrive plus à y accéder.
J’ai essayé avec une version plus ancienne 3.10 ou supérieur, sans succès.
J’ai essayé de refaire l’installation … sans succès

Cordialement


Grégory BODET
Administrateur SIG
Service Information Géographique
03 44 86 76 72<tel:+33344867672>
***@***.******@***.***>

[Agglomération de la Région de Compiègne]<https://www.agglo-compiegne.fr/>


                                      [gadugi_new_logo_geocompiegnois_email]




De : BODET Gregory
Envoyé : vendredi 2 juillet 2021 16:16
À : 'DelazJ/MapsPrinter' ***@***.***>
Objet : RE: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)

Bonjour,

Je viens de réessayer, cela fonctionne. En revanche, on ne peut pas personnaliser le nom de sortie du fichier. Par défaut il concatène le nom du projet et le nom de la mise en page. Pour des améliorations futures, il serait intéressant de pouvoir exporter que le nom paramétré dans l’atlas.

Cordialement

[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/logo_arc_0.png?itok=O1yYKLPQ]<https://www.agglo-compiegne.fr/>

Grégory BODET
Administrateur SIG
03.44.86.76.72
***@***.******@***.***>
ARC
Place de l'Hôtel de Ville - CS 10007
60321 Compiègne Cedex
www.agglo-compiegne.fr<https://www.agglo-compiegne.fr/>
[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/facebook.jpg?itok=NYbcdJFW]<https://www.facebook.com/compiegne.et.son.agglomeration>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/instagram.jpg?itok=H1IfjSDH]<https://www.instagram.com/compiegneagglo/>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/youtube.jpg?itok=fMr4CmUM]<https://www.youtube.com/user/MairiedeCompiegne>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/flicker.jpg?itok=R9yxkLuB]<https://www.flickr.com/photos/compiegne-et-son-agglo/albums>[https://www.agglo-compiegne.fr/sites/default/files/styles/full/public/2020-10/linkedin.jpg?itok=kcIxRFDq]<https://www.linkedin.com/company/compiegne-et-son-agglo/>

[geocompiegnois_2020_reduit_v2]<https://geo.compiegnois.fr/>




P Pensez à l'environnement avant d'imprimer ce message

De : Harrissou Sant-anna ***@***.***
Envoyé : vendredi 2 juillet 2021 12:24
À : DelazJ/MapsPrinter ***@***.******@***.***>>
Cc : BODET Gregory ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Je pense avoir corrigé le bug. Réessayez avec la nouvelle version.

**Comment by DelazJ** [comment]
Bonjour,
> En voulant me servir de nouveau du Plugin MapsPrinter sur la dernière version LTR de QGIS, je n’arrive plus à y accéder.

Càd? Le plugin ne s'installe pas? Un message d'erreur? Autrement, je viens d'essayer sans encombre. Les autres plugins s'installent?
Pour rappel, le plugin n'apparaît nulle part dans l'interface autre que le modeleur ou la boîte à outils Processing (qui doit donc être active elle aussi).

**Comment by gregbodet** [comment]
Bonjour,

Le Plugin n’apparaît pas dans le menu Extension, mais j’ai réussi à le retrouver en passant par « Traitement » ==> « Boite à outils »

Cordialement


Grégory BODET
Administrateur SIG
Service Information Géographique
03 44 86 76 72<tel:+33344867672>
***@***.******@***.***>

[Agglomération de la Région de Compiègne]<https://www.agglo-compiegne.fr/>


                                      [gadugi_new_logo_geocompiegnois_email]



De : Harrissou Sant-anna ***@***.***
Envoyé : jeudi 7 décembre 2023 10:34
À : DelazJ/MapsPrinter ***@***.***>
Cc : BODET Gregory ***@***.***>; Author ***@***.***>
Objet : Re: [DelazJ/MapsPrinter] Algorithm from a folder is not available (#41)


Bonjour,

En voulant me servir de nouveau du Plugin MapsPrinter sur la dernière version LTR de QGIS, je n’arrive plus à y accéder.

Càd? Le plugin ne s'installe pas? Un message d'erreur? Autrement, je viens d'essayer sans encombre. Les autres plugins s'installent?
Pour rappel, le plugin n'apparaît nulle part dans l'interface autre que le modeleur ou la boîte à outils Processing (qui doit donc être active elle aussi).

**Comment by DelazJ** [comment]
Oui, point besoin d'encombrer par défaut le menu de QQGIS vu que tout passe par Processing maintenant. Vous pourrez toujours vous-même l'ajouter en raccourci/menu dans les [Options de Processing](https://docs.qgis.org/3.28/fr/docs/user_manual/processing/configuration.html#menus)
