### ISSUE TITLE
.*gw : format différent

### ISSUE THREAD

**Issue by navivfr** [DelazJ/MapsPrinter#7]
Fichier _._gw
#### Avec QGIS

> 19.109211
> 0.000000
> 0.000000
> -19.109211
> 545454.633843
> 5559723.689351
#### Avec MapsPrinter

> 19.1092110003
> 
> 0.0
> 
> 0.0
> 
> -19.1092110003
> 
> 545454.633843
> 
> 5559723.68935

Un retour à la ligne en trop après chaque données.

**Question** 
Comment faites vous pour avoir une précision supérieur, 10 chiffres après la virgule contre 6 pour QGIS (sauf pour les 2 dernières valeurs) ?

**Comment by DelazJ** [comment]
Pour les retours à la ligne en trop, j'ai vu des formats de fichier .*gw avec ces sauts de ligne, raison pour laquelle je les ai intégrés. Il faut donc enlever le saut de ligne (/n) dans les lignes concernées. Remplacez donc dans le fichier mapsprinter.py (lignes 677- 682) 

> ```
>            with open (worldFileName , "w") as f:
>                f.write ("%s\n\n" % wf[0])
>                f.write ("%s\n\n" % wf[1])
>                f.write ("%s\n\n" % wf[3])
>                f.write ("%s\n\n" % wf[4])
>                f.write ("%s\n\n" % wf[2])
>                f.write ("%s\n" % wf[5])
> ```

par 

> ```
>            with open (worldFileName , "w") as f:
>                f.write ("%s\n" % wf[0])
>                f.write ("%s\n" % wf[1])
>                f.write ("%s\n" % wf[3])
>                f.write ("%s\n" % wf[4])
>                f.write ("%s\n" % wf[2])
>                f.write ("%s" % wf[5])
> ```

Pour la précision des données, je ne crée pas réellement de fonction de génération de world file; je m'appuie sur les fonctions définies déjà dans QGIS. Je pense que la différence doit venir d'un formatage par ailleurs dans QGIS (12 chiffres max dont 6 décimales) alors que la valeur par défaut renvoyée (que j'utilise) est de 12 chiffres max, sans contrainte sur la partie décimale.

**Comment by DelazJ** [comment]
Je ferme ce signalement
