### ISSUE TITLE
Single file export when possible

### ISSUE THREAD

**Issue by zyxel01** [DelazJ/MapsPrinter#9]
Hey DealzJ,
Is there a way to summarize the export in one PDF. The output file is "Scale 1" and appears to be damaged. Are there already solutions to the problem?
thank you in advance!
Zyxel01

**Comment by DelazJ** [comment]
You mean, summarizing the output from different print composers in a single PDF file? In which case NO. The plugin follow what QGIS allows: different composers, different outputs. But if in a multipage or atlas composition you check the box to output a single PDF, yes that composition should be exported in a single file.
> The output file is "Scale 1" and appears to be damaged. Are there already solutions to the problem?

Sorry I don't understand what you are referring to.

**Comment by DelazJ** [comment]
Closing for lack of feedback
